In [776]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/15cse380-nndl-eval/train.csv
/kaggle/input/15cse380-nndl-eval/submission.csv
/kaggle/input/15cse380-nndl-eval/test.csv

In [777]:
train=pd.read_csv('../input/15cse380-nndl-eval/train.csv',na_values=[float('nan')])

In [778]:
float('nan')

nan

In [779]:
train.head()

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted
0,65438,Sales & Marketing,region_7,Master's & above,f,sourcing,1,35,5.0,8,1,0,49,0
1,65141,Operations,region_22,Bachelor's,m,other,1,30,5.0,4,0,0,60,0
2,7513,Sales & Marketing,region_19,Bachelor's,m,sourcing,1,34,3.0,7,0,0,50,0
3,2542,Sales & Marketing,region_23,Bachelor's,m,other,2,39,1.0,10,0,0,50,0
4,48945,Technology,region_26,Bachelor's,m,other,1,45,3.0,2,0,0,73,0

In [780]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [781]:
# train=train.fillna(method=)

In [782]:
train['region']=le.fit_transform(train['region'])
# train.drop('region',inplace=True,axis=1)
# train['region'].corr(train['is_promoted'])

In [783]:
train['department']=le.fit_transform(train['department'])
# train.drop('department',inplace=True,axis=1)

In [784]:
# train['department'].corr(train['is_promoted'])

In [785]:

train=train.join(pd.get_dummies(train.department), how='right', lsuffix='depl', rsuffix='depr')
train.drop('department',axis=1,inplace=True)

In [786]:
train['education']=train['education'].fillna(train['education'].mode(), inplace=True)

In [787]:
train['education']=le.fit_transform(train['education'])

In [788]:
train=train.join(pd.get_dummies(train.education), how='right', lsuffix='edul', rsuffix='edur')

In [789]:
train.drop('education',axis=1,inplace=True)

In [790]:
train.head(5)

,employee_id,region,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,...,0edul,1,2,3,4,5,6,7,8,0edur
0,65438,31,f,sourcing,1,35,5.0,8,1,0,...,0,0,0,0,0,0,0,1,0,1
1,65141,14,m,other,1,30,5.0,4,0,0,...,0,0,0,0,1,0,0,0,0,1
2,7513,10,m,sourcing,1,34,3.0,7,0,0,...,0,0,0,0,0,0,0,1,0,1
3,2542,15,m,other,2,39,1.0,10,0,0,...,0,0,0,0,0,0,0,1,0,1
4,48945,18,m,other,1,45,3.0,2,0,0,...,0,0,0,0,0,0,0,0,1,1

In [791]:

train['gender']=le.fit_transform(train['gender'])
# train['gender'].corr(train['is_promoted'])

In [792]:
train.corr()

,employee_id,region,gender,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,...,0edul,1,2,3,4,5,6,7,8,0edur
employee_id,1.000000,-0.003156,-0.004820,-0.007077,0.002070,0.002257,0.003874,-0.003074,0.009910,0.000423,...,-0.001589,0.006933,0.006593,-0.007622,-0.001597,0.003909,-0.004630,-0.002051,-0.001151,NaN
region,-0.003156,1.000000,0.020593,-0.005477,-0.090896,-0.003291,-0.060801,-0.006629,-0.001598,0.021727,...,0.043397,0.014315,-0.008421,-0.003893,-0.010631,-0.045106,0.011673,0.000586,0.011942,NaN
gender,-0.004820,0.020593,1.000000,0.084110,-0.014274,-0.020438,-0.019230,-0.037366,-0.000113,-0.026997,...,0.144596,0.012234,-0.055598,0.046608,-0.128625,-0.138339,0.073462,0.163207,-0.080139,NaN
no_of_trainings,-0.007077,-0.005477,0.084110,1.000000,-0.079367,-0.059936,-0.055662,-0.045110,-0.006981,0.042668,...,0.047095,0.018012,-0.070251,-0.038096,-0.076762,0.042691,0.033838,0.026596,0.005364,NaN
age,0.002070,-0.090896,-0.014274,-0.079367,1.000000,0.005174,0.657114,-0.026973,-0.010201,-0.046661,...,-0.099707,-0.077152,-0.010306,-0.015973,0.083008,0.056734,-0.033884,0.003249,0.001326,NaN
previous_year_rating,0.002257,-0.003291,-0.020438,-0.059936,0.005174,1.000000,-0.000346,0.349621,0.025329,0.074943,...,0.059067,0.029011,0.025222,0.008188,0.125490,-0.009334,0.026286,-0.137090,-0.053507,NaN
length_of_service,0.003874,-0.060801,-0.019230,-0.055662,0.657114,-0.000346,1.000000,-0.078316,-0.038244,-0.035515,...,-0.069202,-0.053107,-0.006726,-0.040901,0.064769,0.042625,-0.040780,0.005213,0.003575,NaN
KPIs_met >80%,-0.003074,-0.006629,-0.037366,-0.045110,-0.026973,0.349621,-0.078316,1.000000,0.097424,0.075409,...,0.034108,0.028018,-0.007992,-0.006518,0.085789,0.019682,0.018519,-0.118620,-0.007726,NaN
awards_won?,0.009910,-0.001598,-0.000113,-0.006981,-0.010201,0.025329,-0.038244,0.097424,1.000000,0.070748,...,0.000848,0.008200,-0.006593,0.002190,0.000663,0.001532,-0.002102,-0.007537,0.006106,NaN
avg_training_score,0.000423,0.021727,-0.026997,0.042668,-0.046661,0.074943,-0.035515,0.075409,0.070748,1.000000,...,0.520269,-0.052183,-0.215287,-0.037319,-0.120732,0.194358,0.218723,-0.653854,0.479745,NaN
is_promoted,0.001656,0.009058,-0.015061,-0.024587,-0.017485,0.159125,-0.007897,0.219790,0.195716,0.180294,...,0.010926,-0.003083,-0.022193,-0.017535,0.012136,0.016852,-0.011017,-0.032624,0.030661,NaN
0edul,-0.001589,0.043397,0.144596,0.047095,-0.099707,0.059067,-0.069202,0.034108,0.000848,0.520269,...,1.000000,-0.072279,-0.070556,-0.045991,-0.167609,-0.126938,-0.045240,-0.218557,-0.127258,NaN
1,0.006933,0.014315,0.012234,0.018012,-0.077152,0.029011,-0.053107,0.028018,0.008200,-0.052183,...,-0.072279,1.000000,-0.047309,-0.030838,-0.112386,-0.085114,-0.030334,-0.146547,-0.085329,NaN
2,0.006593,-0.008421,-0.055598,-0.070251,-0.010306,0.025222,-0.006726,-0.007992,-0.006593,-0.215287,...,-0.070556,-0.047309,1.000000,-0.030103,-0.109706,-0.083085,-0.029611,-0.143054,-0.083295,NaN
3,-0.007622,-0.003893,0.046608,-0.038096,-0.015973,0.008188,-0.040901,-0.006518,0.002190,-0.037319,...,-0.045991,-0.030838,-0.030103,1.000000,-0.071511,-0.054159,-0.019302,-0.093249,-0.054295,NaN
4,-0.001597,-0.010631,-0.128625,-0.076762,0.083008,0.125490,0.064769,0.085789,0.000663,-0.120732,...,-0.167609,-0.112386,-0.109706,-0.071511,1.000000,-0.197373,-0.070343,-0.339831,-0.197871,NaN
5,0.003909,-0.045106,-0.138339,0.042691,0.056734,-0.009334,0.042625,0.019682,0.001532,0.194358,...,-0.126938,-0.085114,-0.083085,-0.054159,-0.197373,1.000000,-0.053274,-0.257369,-0.149857,NaN
6,-0.004630,0.011673,0.073462,0.033838,-0.033884,0.026286,-0.040780,0.018519,-0.002102,0.218723,...,-0.045240,-0.030334,-0.029611,-0.019302,-0.070343,-0.053274,1.000000,-0.091725,-0.053408,NaN
7,-0.002051,0.000586,0.163207,0.026596,0.003249,-0.137090,0.005213,-0.118620,-0.007537,-0.653854,...,-0.218557,-0.146547,-0.143054,-0.093249,-0.339831,-0.257369,-0.091725,1.000000,-0.258018,NaN
8,-0.001151,0.011942,-0.080139,0.005364,0.001326,-0.053507,0.003575,-0.007726,0.006106,0.479745,...,-0.127258,-0.085329,-0.083295,-0.054295,-0.197871,-0.149857,-0.053408,-0.258018,1.000000,NaN
0edur,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [793]:
train.recruitment_channel=le.fit_transform(train.recruitment_channel)

train=train.join(pd.get_dummies(train.recruitment_channel), how='right', lsuffix='recruitl', rsuffix='recrutr')
train.drop('recruitment_channel',inplace=True,axis=1)

In [794]:
train['previous_year_rating'].fillna(0,inplace=True)
train=train.join(pd.get_dummies(train.previous_year_rating), how='right', lsuffix='prevl', rsuffix='prevr')
train.drop('previous_year_rating',inplace=True,axis=1)

In [795]:
train=train.join(pd.get_dummies(train.region), how='right', lsuffix='regl', rsuffix='regr')
train.drop('region',inplace=True,axis=1)

In [796]:

train.columns

Index([       'employee_id',             'gender',    'no_of_trainings',
                      'age',  'length_of_service',      'KPIs_met >80%',
              'awards_won?', 'avg_training_score',        'is_promoted',
                    '0edul',          '1recruitl',          '2recruitl',
                   '3prevl',             '4prevl',             '5prevl',
                    '6regl',              '7regl',              '8regl',
                    '0edur',             '0prevl',           '1recrutr',
                 '2recrutr',           '0.0prevr',            '1.0regl',
                  '2.0regl',           '3.0prevr',           '4.0prevr',
                 '5.0prevr',                    0,              '1regr',
                    '2regr',                    3,                    4,
                          5,              '6regr',              '7regr',
                    '8regr',                    9,                   10,
                         11,                   12,                   13,
                         14,                   15,                   16,
                         17,                   18,                   19,
                         20,                   21,                   22,
                         23,                   24,                   25,
                         26,                   27,                   28,
                         29,                   30,                   31,
                         32,                   33],
      dtype='object')

In [797]:
train.drop('employee_id',axis=1,inplace=True)
c=train.columns

In [798]:
from sklearn.preprocessing import MinMaxScaler
c

Index([            'gender',    'no_of_trainings',                'age',
        'length_of_service',      'KPIs_met >80%',        'awards_won?',
       'avg_training_score',        'is_promoted',              '0edul',
                '1recruitl',          '2recruitl',             '3prevl',
                   '4prevl',             '5prevl',              '6regl',
                    '7regl',              '8regl',              '0edur',
                   '0prevl',           '1recrutr',           '2recrutr',
                 '0.0prevr',            '1.0regl',            '2.0regl',
                 '3.0prevr',           '4.0prevr',           '5.0prevr',
                          0,              '1regr',              '2regr',
                          3,                    4,                    5,
                    '6regr',              '7regr',              '8regr',
                          9,                   10,                   11,
                         12,                   13,                   14,
                         15,                   16,                   17,
                         18,                   19,                   20,
                         21,                   22,                   23,
                         24,                   25,                   26,
                         27,                   28,                   29,
                         30,                   31,                   32,
                         33],
      dtype='object')

In [799]:
sc=MinMaxScaler()

In [800]:
train['age']=sc.fit_transform(np.array(train['age']).reshape(-1,1))

In [801]:
train['avg_training_score']=sc.fit_transform(np.array(train['avg_training_score']).reshape(-1,1))

In [802]:
train['length_of_service']=sc.fit_transform(np.array(train['length_of_service']).reshape(-1,1))

In [803]:
train.head(20)

,gender,no_of_trainings,age,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted,0edul,1recruitl,...,24,25,26,27,28,29,30,31,32,33
0,0,1,0.375,0.194444,1,0,0.166667,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,1,1,0.250,0.083333,0,0,0.350000,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,1,0.350,0.166667,0,0,0.183333,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,2,0.475,0.250000,0,0,0.183333,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,1,0.625,0.027778,0,0,0.566667,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,1,2,0.275,0.166667,0,0,0.766667,0,1,0,...,0,0,0,0,0,0,0,0,0,0
6,0,1,0.275,0.111111,0,0,0.333333,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,1,1,0.325,0.138889,0,0,0.400000,0,0,0,...,0,0,0,1,0,0,0,0,0,0
8,1,1,0.200,0.111111,0,0,0.733333,0,1,0,...,0,0,0,0,0,0,0,0,0,0
9,1,1,0.300,0.111111,1,0,0.250000,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,1,1,0.250,0.000000,0,0,0.633333,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,1,0.375,0.055556,1,0,0.183333,1,0,0,...,0,0,0,0,0,0,0,1,0,0
12,1,1,0.725,0.111111,1,0,0.166667,0,0,0,...,0,0,0,0,1,0,0,0,0,0
13,1,2,0.475,0.416667,0,0,0.683333,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,1,1,0.425,0.166667,0,0,0.750000,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,1,1,0.425,0.250000,0,0,0.350000,0,0,0,...,0,0,0,0,0,0,0,1,0,0
16,1,1,0.450,0.111111,1,0,0.633333,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,1,1,0.350,0.083333,0,0,0.200000,0,0,0,...,1,0,0,0,0,0,0,0,0,0
18,1,1,0.350,0.194444,1,0,0.116667,0,0,0,...,1,0,0,0,0,0,0,0,0,0
19,1,1,0.425,0.222222,0,0,0.333333,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [804]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,BatchNormalization,Dropout

In [805]:
model=Sequential()
model.add(Dense(input_dim=len(c)-1,units=100,activation='relu'))

model.add(Dense(units=100,activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(units=70,activation='relu'))
model.add(BatchNormalization())
model.add(Dense(units=63,activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(units=60,activation='relu'))
model.add(BatchNormalization())
model.add(Dense(units=30,activation='relu'))
model.add(Dropout(0.3))
# model.add(BatchNormalization())
model.add(Dense(30,activation='relu'))
# model.add(BatchNormalization())
model.add(Dense(1,activation='sigmoid'))

In [806]:
from tensorflow.keras import optimizers
adm = optimizers.Adam(lr=0.0001)

In [807]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [808]:
y=train['is_promoted']
train.drop('is_promoted',axis=1,inplace=True)
x=train
print((x.columns))
print(y)

Index([            'gender',    'no_of_trainings',                'age',
        'length_of_service',      'KPIs_met >80%',        'awards_won?',
       'avg_training_score',              '0edul',          '1recruitl',
                '2recruitl',             '3prevl',             '4prevl',
                   '5prevl',              '6regl',              '7regl',
                    '8regl',              '0edur',             '0prevl',
                 '1recrutr',           '2recrutr',           '0.0prevr',
                  '1.0regl',            '2.0regl',           '3.0prevr',
                 '4.0prevr',           '5.0prevr',                    0,
                    '1regr',              '2regr',                    3,
                          4,                    5,              '6regr',
                    '7regr',              '8regr',                    9,
                         10,                   11,                   12,
                         13,                   14,                   15,
                         16,                   17,                   18,
                         19,                   20,                   21,
                         22,                   23,                   24,
                         25,                   26,                   27,
                         28,                   29,                   30,
                         31,                   32,                   33],
      dtype='object')
0        0
1        0
2        0
3        0
4        0
        ..
48995    0
48996    0
48997    0
48998    0
48999    0
Name: is_promoted, Length: 49000, dtype: int64

In [809]:
print(len(c))

61

In [810]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.20)

In [811]:
len(c)

61

In [812]:
model.fit(xtrain,ytrain,validation_data=[xtest,ytest],epochs=10)

Train on 39200 samples, validate on 9800 samples
Epoch 1/10
39200/39200 [==============================] - 5s 126us/sample - loss: 0.2721 - accuracy: 0.9126 - val_loss: 0.2367 - val_accuracy: 0.9134
Epoch 2/10
39200/39200 [==============================] - 4s 99us/sample - loss: 0.2159 - accuracy: 0.9230 - val_loss: 0.2006 - val_accuracy: 0.9305
Epoch 3/10
39200/39200 [==============================] - 4s 100us/sample - loss: 0.1907 - accuracy: 0.9331 - val_loss: 0.1954 - val_accuracy: 0.9319
Epoch 4/10
39200/39200 [==============================] - 4s 103us/sample - loss: 0.1823 - accuracy: 0.9362 - val_loss: 0.1924 - val_accuracy: 0.9327
Epoch 5/10
39200/39200 [==============================] - 4s 99us/sample - loss: 0.1768 - accuracy: 0.9385 - val_loss: 0.1741 - val_accuracy: 0.9388
Epoch 6/10
39200/39200 [==============================] - 4s 99us/sample - loss: 0.1743 - accuracy: 0.9393 - val_loss: 0.1807 - val_accuracy: 0.9383
Epoch 7/10
39200/39200 [==============================] - 4s 98us/sample - loss: 0.1715 - accuracy: 0.9405 - val_loss: 0.1741 - val_accuracy: 0.9393
Epoch 8/10
39200/39200 [==============================] - 4s 99us/sample - loss: 0.1684 - accuracy: 0.9413 - val_loss: 0.1798 - val_accuracy: 0.9377
Epoch 9/10
39200/39200 [==============================] - 4s 98us/sample - loss: 0.1664 - accuracy: 0.9418 - val_loss: 0.1782 - val_accuracy: 0.9386
Epoch 10/10
39200/39200 [==============================] - 4s 98us/sample - loss: 0.1668 - accuracy: 0.9419 - val_loss: 0.1785 - val_accuracy: 0.9382

In [815]:
model.fit(xtest,ytest,epochs=9)

Train on 9800 samples
9800/9800 [==============================] - 2s 164us/sample - loss: 0.1837 - accuracy: 0.9363

In [814]:
model.evaluate(xtest,ytest)

9800/9800 [==============================] - 0s 40us/sample - loss: 0.1785 - accuracy: 0.9382

[0.17851250001362393, 0.9381633]

In [213]:

ypred=model.predict(xtest)

In [214]:
from sklearn.metrics import accuracy_score
ypred=ypred>0.5
ypred=ypred*1
accuracy_score(ypred,ytest)

0.9490816326530612

In [720]:
test=pd.read_csv('../input/15cse380-nndl-eval/test.csv',na_values=[float('nan')])

In [721]:
# test=test.drop('department',axis=1)
# test=test.drop('recruitment_channel',axis=1)
# test=test.drop('employee_id',axis=1)
test['region']=le.fit_transform(test['region'])
test['department']=le.fit_transform(test['department'])

In [722]:
test['age']=sc.fit_transform(np.array(test['age']).reshape(-1,1))
test['avg_training_score']=sc.fit_transform(np.array(test['avg_training_score']).reshape(-1,1))
test['length_of_service']=sc.fit_transform(np.array(test['length_of_service']).reshape(-1,1))

In [723]:
test['education']=test['education'].fillna(test['education'].mode(), inplace=True)
test['education']=le.fit_transform(test['education'])
test['gender']=le.fit_transform(test['gender'])
test['region']=le.fit_transform(test['region'])

In [724]:
len(test)

5808

In [725]:
test=test.join(pd.get_dummies(test.department), how='right', lsuffix='deptl', rsuffix='deptr')
test.drop('department',axis=1,inplace=True)

In [726]:
test=test.join(pd.get_dummies(test.education), how='right', lsuffix='edul', rsuffix='edur')
test.drop('education',axis=1,inplace=True)

In [727]:
test=test.join(pd.get_dummies(test.region), how='right', lsuffix='regl', rsuffix='regr')
test.drop('region',axis=1,inplace=True)

In [728]:
test.drop('employee_id',inplace=True,axis=1)
len(test.columns)

53

In [729]:
test.recruitment_channel=le.fit_transform(test.recruitment_channel)
test=test.join(pd.get_dummies(test.recruitment_channel), how='right', lsuffix='recruitl', rsuffix='recruitr')
test.drop('recruitment_channel',axis=1,inplace=True)

In [730]:
test['previous_year_rating'].fillna(0, inplace=True)
test.previous_year_rating=le.fit_transform(test.previous_year_rating)
test=test.join(pd.get_dummies(test.previous_year_rating), how='right', lsuffix='prevl', rsuffix='prevr')
test.drop('previous_year_rating',axis=1,inplace=True)

In [731]:
print(test.columns)
len(test.columns)

Index([            'gender',    'no_of_trainings',                'age',
        'length_of_service',      'KPIs_met >80%',        'awards_won?',
       'avg_training_score',              '0edul',              '1regl',
                    '2regl',              '3regl',              '4regl',
                    '5regl',              '6regl',              '7regl',
                    '8regl',              '0edur',          '0recruitl',
                    '1regr',              '2regr',              '3regr',
                    '4regr',              '5regr',              '6regr',
                    '7regr',              '8regr',                    9,
                         10,                   11,                   12,
                         13,                   14,                   15,
                         16,                   17,                   18,
                         19,                   20,                   21,
                         22,                   23,                   24,
                         25,                   26,                   27,
                         28,                   29,                   30,
                         31,                   32,                   33,
                '0recruitr',             '1prevl',             '2prevl',
                          0,             '1prevr',             '2prevr',
                          3,                    4,                    5],
      dtype='object')

60

In [732]:
sub=pd.read_csv('../input/15cse380-nndl-eval/submission.csv')

In [733]:
sub=sub['is_promoted']

In [734]:
print(test.columns)
xtrain.columns

Index([            'gender',    'no_of_trainings',                'age',
        'length_of_service',      'KPIs_met >80%',        'awards_won?',
       'avg_training_score',              '0edul',              '1regl',
                    '2regl',              '3regl',              '4regl',
                    '5regl',              '6regl',              '7regl',
                    '8regl',              '0edur',          '0recruitl',
                    '1regr',              '2regr',              '3regr',
                    '4regr',              '5regr',              '6regr',
                    '7regr',              '8regr',                    9,
                         10,                   11,                   12,
                         13,                   14,                   15,
                         16,                   17,                   18,
                         19,                   20,                   21,
                         22,                   23,                   24,
                         25,                   26,                   27,
                         28,                   29,                   30,
                         31,                   32,                   33,
                '0recruitr',             '1prevl',             '2prevl',
                          0,             '1prevr',             '2prevr',
                          3,                    4,                    5],
      dtype='object')

Index([            'gender',    'no_of_trainings',                'age',
        'length_of_service',      'KPIs_met >80%',        'awards_won?',
       'avg_training_score',          '0recruitl',          '1recruitl',
                '2recruitl',             '3prevl',             '4prevl',
                   '5prevl',              '6regl',              '7regl',
                    '8regl',           '0recrutr',           '1recrutr',
                 '2recrutr',            '1.0regl',            '2.0regl',
                 '3.0prevr',           '4.0prevr',           '5.0prevr',
                          0,              '1regr',              '2regr',
                          3,                    4,                    5,
                    '6regr',              '7regr',              '8regr',
                          9,                   10,                   11,
                         12,                   13,                   14,
                         15,                   16,                   17,
                         18,                   19,                   20,
                         21,                   22,                   23,
                         24,                   25,                   26,
                         27,                   28,                   29,
                         30,                   31,                   32,
                         33],
      dtype='object')

In [735]:
# model.evaluate(test,sub)
ysub=model.predict(test)
ysub=ysub>0.75
ysub=ysub*1
# from sklearn.metrics import accuracy_score
# print(accuracy_score(ysub,sub))

ValueError: Error when checking input: expected dense_112_input to have shape (58,) but got array with shape (60,)

In [547]:
for i in xstest.columns[1:]:
    xstest=xstest.drop(i,axis=1)

In [548]:
xstest['is_promoted']=ysub
xstest.to_csv('cse17314.csv',index=False)
xstest['is_promoted'].value_counts()

ValueError: Length of values does not match length of index

In [387]:
xstest

      employee_id  is_promoted
0           38921            0
1           47802            0
2           48171            0
3           31522            0
4           46116            0
...           ...          ...
5803         3030            0
5804        74592            0
5805        13918            0
5806        13614            0
5807        51526            0

[5808 rows x 2 columns]